### ISSUE TITLE
redirect_uri_mismatch with expo and ios?

### ISSUE THREAD

**Issue by Tzikas** [hasura/react-native-auth-boilerplate#11]
Thanks so much for this boiler.  I'm trying to implement google auth with ios, and I'm getting `redirect_uri_mismatch` I changed the app.json bundle identifier to match what i had in the Google API console.  Could I be doing something else wrong?  Do I have to run exp build:android first and add the android package as well?

**Comment by wawhal** [comment]
@Tzikas are you using the boilerplate in the Expo app or you are making standalone builds?
In your Google Cloud Console:
- If you are using it in Expo app, you have to set the bundle identifier to `host.exp.exponent`.
- If you using standalone expo builds, copy the bundle identifier from your `app.json` 

Hope that helps.

**Comment by Tzikas** [comment]
@wawhal That did it thanks!  Can you explain why?? I searched the project but, can't find that `host.exp.exponent` anywhere but where I included it in the app.json file.  

Now i ran into `Network request failed
- node_modules/whatwg-fetch/fetch.js:441:29 in onerro` after that but that's a new issue.  I'll try to sort it out.  

Also does exp build:ios build a standalone? And in that situation can I name my bundleIdentifier anything I'd like.  Thanks again for all the help.

**Comment by wawhal** [comment]
@Tzikas  As per my understanding, `host.exp.exponent` is the bundle identifier for the Expo app. So when you are running the project from the Expo app, the bundle identifier would be `host.exp.exponent`

Yes `exp build:ios` makes a standalone build. Yes you can rename your bundle identifier in that case as far as you are sticking to the bundle identifier format. Check https://stackoverflow.com/questions/28979874/what-is-correct-format-of-bundle-identifier-in-ios

I am closing this issue for now. Open another issue in case you have other problems.
